### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by fu33** [cvlab-yonsei/OIMNetPlus#1]
你的示例图是怎么得出来的

**Comment by sanghoooon** [comment]
Hello @fu33 , I am happy to address your issue in English :)

**Comment by fu33** [comment]
How did you get your sample picture？

**Comment by sanghoooon** [comment]
I got the qualitative results in our paper by modifying the code [here](https://github.com/serend1p1ty/SeqNet/blob/master/demo.py).

I saved the retrieval results (predictions for each query image) into a separate .pkl file in prior for easy implementation.
Wish you good luck!

**Comment by sanghoooon** [comment]
Refer to #2.
We hope this helps.

**Comment by nooralanwar** [comment]
Thank you that was very helpful. Do you know how to visualize the feature maps input to REID heads?
